Add semaphore configuration

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -10,5 +10,5 @@ MIX_ENV=test mix compile --force --warnings-as-errors || { echo 'Please fix all 
 if [ ! $CI ]; then
   MIX_ENV=test mix test || { echo 'Tests failed!'; exit 1; }
 else
-  MIX_ENV=test mix coveralls.travis || { echo 'Tests failed!'; exit 1; }
+  MIX_ENV=test mix coveralls.semaphore || { echo 'Tests failed!'; exit 1; }
 fi
